import Head from 'next/head'
import Header from '/components/Header/Header'
import Tabs from '/components/Tabs/Tabs'
import Tool from '/components/tool/tool'
import ListCart from '/components/ListCart/ListCart'
import { useState } from 'react'
import styles from '/styles/Home.module.css'


export default function Home() {

  const [toolType, setToolType] = useState('Nomenclature');
  const [listOfCards, setListOfCards] = useState([]);
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Tabs setToolType={setToolType} />
      <div className={styles.toolListZone}>
        <Tool toolType={toolType} setListOfCards={setListOfCards} listOfCards={listOfCards}/>
        <ListCart listOfCards={listOfCards}/>
      </div>
      <p>Pour dépasser les limitations et créer des cartes à l’infinie <a>passez à Card+</a></p>
      
    </div>
  )
}
